---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      network:
        - ["forwarded_port", {guest: 8000, host: 8000}]
  - name: centos-7.1
    driver:
      network:
        - ["forwarded_port", {guest: 8000, host: 8001}]

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    attributes:
